In [2]:
from sklearn.datasets import load_diabetes

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [3]:
X,y = load_diabetes(return_X_y=True)

In [4]:
print(X.shape)
print(y.shape)

(442, 10)
(442,)


In [5]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [6]:
reg = LinearRegression()
reg.fit(X_train,y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [7]:
print(reg.coef_)
print(reg.intercept_)

[  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]
151.88331005254167


In [9]:

y_pred = reg.predict(X_test)
r2_score(y_test,y_pred)

0.439933866156897

In [10]:

import random

class MBGDRegressor:
    
    def __init__(self,batch_size,learning_rate=0.01,epochs=100):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size
        
    def fit(self,X_train,y_train):
        # init your coefs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            
            for j in range(int(X_train.shape[0]/self.batch_size)):
                
                idx = random.sample(range(X_train.shape[0]),self.batch_size)
                
                y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_
                #print("Shape of y_hat",y_hat.shape)
                intercept_der = -2 * np.mean(y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)

                coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)
        
        print(self.intercept_,self.coef_)
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [11]:
import random
random.sample(range(1,100),10)


[59, 6, 78, 50, 21, 57, 44, 90, 83, 16]

In [12]:
X_train[[59, 6, 78, 50, 21, 57, 44, 90, 83, 16]]

array([[-0.00914709, -0.04464164, -0.06225218, -0.07452744, -0.02358421,
        -0.01321352,  0.00446045, -0.03949338, -0.03581619, -0.04664087],
       [-0.00914709,  0.05068012,  0.17055523,  0.01498668,  0.03007796,
         0.03375875, -0.02131102,  0.03430886,  0.03365381,  0.03205916],
       [ 0.01628068, -0.04464164, -0.04500719, -0.05731319, -0.03459183,
        -0.05392282,  0.07441156, -0.0763945 , -0.04257085,  0.04034337],
       [ 0.07440129, -0.04464164,  0.03151747,  0.10105796,  0.04658939,
         0.03689023,  0.01550536, -0.00259226,  0.03365381,  0.04448548],
       [ 0.07440129, -0.04464164,  0.0347509 ,  0.09417226,  0.05759701,
         0.02029337,  0.02286863, -0.00259226,  0.07379893, -0.02178823],
       [ 0.06713621,  0.05068012, -0.02991782,  0.05743704, -0.00019301,
        -0.01571871,  0.07441156, -0.05056372, -0.03845972,  0.00720652],
       [ 0.04534098,  0.05068012, -0.03530688,  0.0631866 , -0.00432087,
        -0.00162703, -0.01026611, -0.00259226

In [15]:
mbr = MBGDRegressor(batch_size=int(X_train.shape[0]/50),learning_rate=0.01,epochs=50)

In [16]:
X_train.shape

(353, 10)

In [17]:
mbr.fit(X_train,y_train)

150.9717014274697 [  29.8502858  -144.62922803  458.02824592  311.90027153  -29.64213184
 -101.36113758 -192.67830522  109.83587307  408.68949858  102.63619232]


In [18]:
int(353/10)

35

In [19]:
y_pred = mbr.predict(X_test)

In [21]:
r2_score(y_test,y_pred)

0.45333114599384305

In [22]:
from sklearn.linear_model import SGDRegressor

In [23]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.2)

In [25]:

batch_size = 35

for i in range(100):
    
    idx = random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[idx],y_train[idx])


In [26]:
sgd.coef_

array([  51.16952354, -134.56531092,  417.27183436,  274.69353685,
         -5.16060836,  -72.74521561, -189.87289149,  103.76053202,
        394.94474775,  142.22212644])

In [27]:
sgd.intercept_

array([155.35678364])

In [28]:
y_pred = sgd.predict(X_test)

In [29]:
r2_score(y_test,y_pred)

0.449246828218821